= Testing the Branded iOS App
:toc: right
:description: Testing the branded iOS app is a vital before rolling out. This guide shows how to do it. 

== Introduction

{description}

== Distribute the File

You can distribute the file with the .ipa extension, like our example MyBiz iOS App-3.4.211.ipa, from your {customer-owncloud-url}[customer.owncloud.com] account to your beta testers. To do this you need a macOS computer, an iPhone or iPad registered in your Apple developer account, and the iTunes account associated with your Apple developer account.

1. Connect your registered iPhone or iPad to a Mac running iTunes.
2. Double-click your iOS .ipa file.
3. You should see your device in the upper left corner of your iTunes windows. Click on it.
4. To make the branded iOS app visible in your iTunes apps list including an install button, click the btn:[Apps] button.
5. The Install button changes to btn:[Will Install].
6. To install the branded iOS app on your device, click the btn:[Sync] button in the lower-right corner.

Your other testers can now install and test your app on their registered iPhones and iPads just like any other app from iTunes.

If you have the Enterprise Apple developer account, there is no limit on the number of testing devices, and they do not have to be registered.

== Getting Crash Reports From Testers

iOS automatically records crash logs when apps crash. Your testers can retrieve and send these logs to you. They must follow these steps:

1. Connect the testing device to a Mac computer running iTunes.
2. The crash logs are automatically downloaded to `~/Library/Logs/CrashReporter/MobileDevice`
3. Attach the relevant log files to email and send them to you.
